services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - ai-network

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openwebuiproject
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - OPEN_WEB_UI_API_KEY=${OPEN_WEB_UI_API_KEY}
      - OPEN_WEB_UI_API_URL=http://open-webui:8080
      - DB_URL=db:5432
    ports:
      - "8000:8000"
    depends_on:
      - open-webui
      - db
    networks:
        - ai-network

networks:
  ai-network:

volumes:
  postgres_data:
  open-webui-data: